### ISSUE TITLE
in3_map ，Internal Mic work fine 

### ISSUE THREAD

**Issue by youling257** [AndyLavr/Aspire-SW5-012_Kernel_4.8#1]
ASoC: Intel: bytcr_rt5640: quirks for Insyde devices ，Signed-off-by me，should be in3_map

**Comment by youling257** [comment]
From 18fda151974c4f32d97da13a5709badf37e7d5fb Mon Sep 17 00:00:00 2001
From: youling257 <youling257@gmail.com>
Date: Mon, 3 Oct 2016 02:05:33 +0800
Subject: [PATCH] cube i7 cx

Signed-off-by: youling257 <youling257@gmail.com>
---
 sound/soc/intel/boards/bytcr_rt5640.c | 22 ++++++++++++++++++++++
 1 file changed, 22 insertions(+)

diff --git a/sound/soc/intel/boards/bytcr_rt5640.c b/sound/soc/intel/boards/bytcr_rt5640.c
index bff77a1..6e3a395 100644
--- a/sound/soc/intel/boards/bytcr_rt5640.c
+++ b/sound/soc/intel/boards/bytcr_rt5640.c
@@ -389,6 +389,28 @@ static const struct dmi_system_id byt_rt5640_quirk_table[] = {
 						 BYT_RT5640_SSP0_AIF1),
 
 	},
+	{
+		.callback = byt_rt5640_quirk_cb,
+		.matches = {
+			DMI_MATCH(DMI_SYS_VENDOR, "Insyde"),
+			DMI_MATCH(DMI_PRODUCT_NAME, "ONDA Tablet"),
+		},
+		.driver_data = (unsigned long *)(BYT_RT5640_IN1_MAP |
+						 BYT_RT5640_MCLK_EN |
+						 BYT_RT5640_SSP0_AIF1),
+
+	},
+	{
+		.callback = byt_rt5640_quirk_cb,
+		.matches = {
+			DMI_MATCH(DMI_SYS_VENDOR, "Insyde"),
+			DMI_MATCH(DMI_PRODUCT_NAME, "hampoo"),
+		},
+		.driver_data = (unsigned long *)(BYT_RT5640_IN1_MAP |
+						 BYT_RT5640_MCLK_EN |
+						 BYT_RT5640_SSP0_AIF1),
+
+	},
 	{}
 };
 
-- 
2.9.3


From 8ce9fd1ede3fd6778698e1da9abc0bb91d6e8f50 Mon Sep 17 00:00:00 2001
From: youling257 <youling257@gmail.com>
Date: Sun, 20 Nov 2016 21:56:44 +0800
Subject: [PATCH] insyde

Signed-off-by: youling257 <youling257@gmail.com>
---
 sound/soc/intel/boards/bytcr_rt5640.c | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/sound/soc/intel/boards/bytcr_rt5640.c b/sound/soc/intel/boards/bytcr_rt5640.c
index fb50ea9..4d706bb 100644
--- a/sound/soc/intel/boards/bytcr_rt5640.c
+++ b/sound/soc/intel/boards/bytcr_rt5640.c
@@ -393,7 +393,7 @@ static const struct dmi_system_id byt_rt5640_quirk_table[] = {
 			DMI_MATCH(DMI_SYS_VENDOR, "Insyde"),
 			DMI_MATCH(DMI_PRODUCT_NAME, "ONDA Tablet"),
 		},
-		.driver_data = (unsigned long *)(BYT_RT5640_IN1_MAP |
+		.driver_data = (unsigned long *)(BYT_RT5640_IN3_MAP |
 						 BYT_RT5640_MCLK_EN |
 						 BYT_RT5640_SSP0_AIF1),
 	},
@@ -403,7 +403,7 @@ static const struct dmi_system_id byt_rt5640_quirk_table[] = {
 			DMI_MATCH(DMI_SYS_VENDOR, "Insyde"),
 			DMI_MATCH(DMI_PRODUCT_NAME, "hampoo"),
 		},
-		.driver_data = (unsigned long *)(BYT_RT5640_IN1_MAP |
+		.driver_data = (unsigned long *)(BYT_RT5640_IN3_MAP |
 						 BYT_RT5640_MCLK_EN |
 						 BYT_RT5640_SSP0_AIF1),
 
-- 
2.10.1

**Comment by AndyLavr** [comment]
Thank you.
