### ISSUE TITLE
Backlight work，pwm patch and DSDT patch 

### ISSUE THREAD

**Issue by youling257** [AndyLavr/Aspire-SW5-012_Kernel_4.8#2]
https://plus.google.com/116937366969544577777/posts/fc7y2oAirh5

**Comment by youling257** [comment]
--- 1dsdt.dsl
+++ dsdt.dsl
@@ -9582,12 +9582,7 @@
                     Return (Zero)
                 }
 
-                If (OSSL & 0x80)
-                {
-                    Return (0x0F)
-                }
-
-                Return (Zero)
+                Return (0x0F)
             }
 
             Method (_PS3, 0, NotSerialized)  // _PS3: Power State 3
@@ -9640,12 +9635,7 @@
                     Return (Zero)
                 }
 
-                If (OSSL & 0x80)
-                {
-                    Return (0x0F)
-                }
-
-                Return (Zero)
+                Return (0x0F)
             }
 
             Method (_PS3, 0, NotSerialized)  // _PS3: Power State 3

**Comment by AndyLavr** [comment]
On the Acer Aspire Switch 10 is not suitable.

**Comment by youling257** [comment]
these three pwm patch，https://drive.google.com/drive/folders/0B_uxdqSfzNGwTjF2M2w2VDBzb0k ，and compile dsdt.hex into kernel，backlight not work for you ? can you upload your dsdt.dsl ?

**Comment by AndyLavr** [comment]
https://github.com/AndyLavr/Aspire-SW5-012_Kernel_4.8/commit/b45b1de4c4c29f3809f9fca4f34eabb6e90c80eb

https://github.com/AndyLavr/Aspire-SW5-012_Kernel_4.8/commit/7e5515673ec1179fd41c80e8b36368d2bef44561

This fix is bad, the kernel is no build:
2-3-pwm-lpss-Add-intel-gfx-as-consumer-device-in-lookup-table.patch

**Comment by AndyLavr** [comment]
dsdt.dsl 
I sent to your email

**Comment by youling257** [comment]
I can't find pwm in your dsdt，the pwm patch and dsdt patch for drm:pwm_setup_backlight [i915]] *ERROR* Failed to own the pwm chip this bug ，your dmesg，http://4pda.ru/forum/dl/post/8954902/dmesg.txt，can't find pwm error .

**Comment by youling257** [comment]
https://github.com/burzumishi/linux-baytrail-flexx10/issues/15#issuecomment-249163715
https://github.com/burzumishi/linux-baytrail-flexx10/issues/15#issuecomment-245825017
such as z3735G Flexx 9 and z3735f Flexx 10 tablets are very different. 
may be your tablet need this ， https://github.com/burzumishi/linux-baytrail-flexx10/issues/15#issuecomment-245825017

**Comment by AndyLavr** [comment]
[    0.000000] Linux version 4.8.4 (bamston@Acer-sw5-012) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) ) #1 SMP PREEMPT Sun Oct 23 15:10:58 EEST 2016 (Ubuntu 4.8.4-27.29+IntelAtom-acerium 4.8.4)

you have the kernel 4.8.4
4.8.8 patch branch

http://acerium.ru/english/

Look at the bottom of the page

**Comment by AndyLavr** [comment]
$ uname -a
Linux lavrandy-Aspire-SW5-012 4.8.9-muqss #1 SMP PREEMPT Mon Nov 21 18:56:37 EET 2016 x86_64 x86_64 x86_64 GNU/Linux
$ dmesg | egrep ERROR
[    0.206252] acpi PNP0A08:00: _OSC failed (AE_ERROR); disabling ASPM
[    4.442076] [drm:pwm_setup_backlight [i915]] *ERROR* Failed to own the pwm chip: pwm_lpss

**Comment by youling257** [comment]
yes，use the three pwm patch，it will pwm chip: pwm_lpss ，so need DSDT patch.

**Comment by AndyLavr** [comment]
Repeat:

This fix is bad, the kernel is no build:
2-3-pwm-lpss-Add-intel-gfx-as-consumer-device-in-lookup-table.patch

It does not work, and no effect:

http://home.ix.netcom.com/~jjingber/0007-intel_baytrail_backlight.patch
i915 kernel module needs i915.force_backlight_pmic=1

**Comment by youling257** [comment]
ok，build include 2-3-pwm-lpss-Add-intel-gfx-as-consumer-device-in-lookup-table.patch ，wait for the result . 
you send my dsdt is right ? miss much information.

**Comment by AndyLavr** [comment]
Users will not be able fix correct the DSDT,  need another solution.

**Comment by AndyLavr** [comment]
But in both I get an error in the final linking:
ERROR: "pwm_add_table" [drivers/pwm/pwm-lpss-platform.ko] undefined!

**Comment by youling257** [comment]
CONFIG_PWM=y
CONFIG_PWM_CRC=y
CONFIG_I2C_DESIGNWARE_PLATFORM=y
CONFIG_I2C_DESIGNWARE_PCI=y
CONFIG_INTEL_SOC_PMIC=y
CONFIG_DRM_I915=m
CONFIG_PWM_LPSS=y
CONFIG_PWM_LPSS_PCI=y
CONFIG_PWM_LPSS_PLATFORM=y
CONFIG_X86_INTEL_LPSS=y

**Comment by AndyLavr** [comment]
Ok, the build started. Results are reported.

**Comment by AndyLavr** [comment]
Build fine.

$ dmesg 
[    0.000000] Linux version 4.8.10-muqss (andylavr@buildbox) (gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12) ) #1 SMP PREEMPT Tue Nov 22 15:04:57 EET 2016 (Ubuntu 4.8.10-27.29+MuQSS+IntelAtom-acerium 4.8.10)
[    0.000000] Command line: BOOT_IMAGE=/@/boot/vmlinuz-4.8.10-muqss root=UUID=1897a202-d46f-4aa6-aa5b-b9a7cf9aaed2 ro rootflags=subvol=@ crashkernel=384M-:128M threadirqs i915.force_backlight_pmic=1

$ dmesg | egrep ERROR
[    0.204279] acpi PNP0A08:00: _OSC failed (AE_ERROR); disabling ASPM
[    4.472071] [drm:pwm_setup_backlight [i915]] *ERROR* Failed to own the pwm chip: pwm_lpss

**Comment by AndyLavr** [comment]
In my DSDT no rows --> If (OSSL & 0x80)

?

**Comment by youling257** [comment]
Device (PWM1)
        {
            Name (_ADR, Zero)  // _ADR: Address
            Name (_HID, "80860F09" /* Intel PWM Controller */)  // _HID: Hardware ID
            Name (_CID, "80860F09" /* Intel PWM Controller */)  // _CID: Compatible ID
            Name (_DDN, "Intel(R) PWM Controller #1 - 80860F08")  // _DDN: DOS Device Name
            Name (_UID, One)  // _UID: Unique ID
            Name (RBUF, ResourceTemplate ()

Device (PWM2)
        {
            Name (_ADR, Zero)  // _ADR: Address
            Name (_HID, "80860F09" /* Intel PWM Controller */)  // _HID: Hardware ID
            Name (_CID, "80860F09" /* Intel PWM Controller */)  // _CID: Compatible ID
            Name (_DDN, "Intel(R) PWM Controller #2 - 80860F09")  // _DDN: DOS Device Name
            Name (_UID, 0x02)  // _UID: Unique ID
            Name (RBUF, ResourceTemplate ()

your dsdt no these .
